# Generated by Django 5.2.9 on 2026-04-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='What did you buy?', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('NEED', 'Need (Survival)'), ('WANT', 'Want (Lifestyle)'), ('INVESTMENT', 'Asset/Investment (Future)'), ('DEBT_GOOD', 'Good Debt (Leverage)'), ('DEBT_BAD', 'Bad Debt (Wealth Destroyer)')], max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
