# ─────────────────────────────────────────────────────────────────────────────
# api/migrations/0001_initial.py — Initial Database Migration
# ─────────────────────────────────────────────────────────────────────────────
# THIS FILE WAS AUTO-GENERATED by Django. Do not edit it manually.
# It was created by running: python manage.py makemigrations api
#
# WHAT IS A MIGRATION?
#   A migration is a versioned script that describes how to change the database
#   schema. Instead of writing raw SQL (CREATE TABLE, ALTER TABLE, DROP TABLE),
#   you define models in Python (models.py), and Django generates the migration.
#
# WHY MIGRATIONS EXIST:
#   Without migrations, every developer would need to manually apply SQL changes
#   to their local database whenever the schema changes. Migrations make schema
#   changes reproducible, reversible, and trackable in git.
#
# MIGRATION LIFECYCLE:
#   1. You edit api/models.py (add a field, new model, etc.)
#   2. Run: python manage.py makemigrations api
#      → Django compares the current model state to the last migration's state
#      → Generates a new 000N_description.py file with the diff
#   3. Run: python manage.py migrate
#      → Django reads ALL un-applied migrations in order
#      → Executes each one's operations against the database
#      → Records the migration name in the django_migrations table
#
# THIS SPECIFIC MIGRATION (0001_initial):
#   This is the FIRST migration for the 'api' app — it creates the
#   api_transaction table from scratch.
#   'initial = True' tells Django this is the first migration for this app.
#
# HOW TO APPLY IT:
#   python manage.py migrate
#   → Runs this migration → creates the api_transaction table in db.sqlite3
#
# HOW TO REVERSE IT (undo):
#   python manage.py migrate api zero
#   → Reverts all migrations for the 'api' app → drops api_transaction table
#
# WHAT SQL THIS GENERATES (for SQLite):
#   CREATE TABLE "api_transaction" (
#     "id"       integer NOT NULL PRIMARY KEY AUTOINCREMENT,
#     "title"    varchar(100) NOT NULL,
#     "amount"   decimal NOT NULL,
#     "category" varchar(20) NOT NULL,
#     "date"     date NOT NULL
#   );
# ─────────────────────────────────────────────────────────────────────────────

# Generated by Django 5.2.9 on 2026-04-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    # initial=True marks this as the first migration for this app.
    # Django uses this to know that there's nothing to depend on within this app.
    initial = True

    # dependencies: list of other migrations that MUST run before this one.
    # Empty here because this is the first migration — nothing to depend on.
    # Future migrations would list this one:
    #   dependencies = [('api', '0001_initial')]
    dependencies = [
    ]

    # operations: the list of schema changes to apply.
    # Each operation can be applied (migrate) or reversed (migrate --backwards).
    operations = [
        # migrations.CreateModel() generates a CREATE TABLE statement.
        # It takes the model name and a list of fields.
        migrations.CreateModel(
            name='Transaction',  # Creates the table 'api_transaction'
            fields=[
                # Auto-generated primary key.
                # BigAutoField = 64-bit auto-incrementing integer.
                # auto_created=True means Django generated this — it's not in models.py.
                # primary_key=True → this column is the PK.
                # verbose_name='ID' → label shown in Django admin.
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),

                # title column: VARCHAR(100) NOT NULL
                # help_text appears in admin forms and DRF browsable API.
                ('title', models.CharField(help_text='What did you buy?', max_length=100)),

                # amount column: DECIMAL(12, 2) NOT NULL
                # DecimalField → exact decimal arithmetic (no floating-point errors).
                # Stores values like 450.75 or 50000.00 accurately.
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),

                # category column: VARCHAR(20) NOT NULL with choices constraint
                # choices= is enforced by Django at the application layer (forms/serializers)
                # but NOT by a database-level CHECK constraint in SQLite.
                # Valid values: NEED, WANT, INVESTMENT, DEBT_GOOD, DEBT_BAD
                ('category', models.CharField(choices=[('NEED', 'Need (Survival)'), ('WANT', 'Want (Lifestyle)'), ('INVESTMENT', 'Asset/Investment (Future)'), ('DEBT_GOOD', 'Good Debt (Leverage)'), ('DEBT_BAD', 'Bad Debt (Wealth Destroyer)')], max_length=20)),

                # date column: DATE NOT NULL (auto-set on insert)
                # auto_now_add=True → Django automatically sets this to today's date
                # when Transaction.objects.create() is called.
                # The column is marked editable=False by Django — you can't override it.
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
