# ─────────────────────────────────────────────────────────────────────────────
# core/urls.py — Root URL Configuration (FIN-OS Core Server)
# ─────────────────────────────────────────────────────────────────────────────
# This is the MASTER URL router — Django reads this file first for every
# incoming HTTP request. Think of it as the traffic director:
#
#   /admin/*       → Django's auto-generated admin interface
#   /*             → Delegated to finos/urls.py (our FIN-OS app)
#
# HOW URL RESOLUTION WORKS:
#   1. Request arrives: GET /investor/
#   2. Django reads ROOT_URLCONF = 'core.urls' from settings.py
#   3. Iterates through urlpatterns list from top to bottom
#   4. 'admin/' → no match (path is /investor/)
#   5. '' (empty string) → matches! Django strips '' (nothing) and passes
#      the full path '/investor/' to finos/urls.py
#   6. finos/urls.py matches 'investor/' → calls views.investor()
#
# DESIGN PRINCIPLE — Why separate core/urls.py from finos/urls.py?
#   Modularity. The core urlconf is the project-level router.
#   Each app (finos, api, etc.) manages its own URL patterns.
#   This makes it easy to add or remove an entire feature area
#   by commenting out one include() line here.
# ─────────────────────────────────────────────────────────────────────────────
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # Django's built-in admin site.
    # admin.site.urls is itself a urlconf — it contains patterns for:
    #   /admin/           → admin index (lists all registered model groups)
    #   /admin/login/     → login page
    #   /admin/logout/    → logout
    #   /admin/<app>/<model>/          → model list view
    #   /admin/<app>/<model>/add/      → create new record
    #   /admin/<app>/<model>/<pk>/     → edit existing record
    #   /admin/<app>/<model>/<pk>/delete/ → delete confirmation
    # All of these are auto-generated by Django based on which models
    # are registered in each app's admin.py.
    path('admin/', admin.site.urls),

    # Delegate EVERYTHING ELSE to the finos app's urlconf.
    # The empty string '' means: match from the very start of the path (root /).
    # include() imports finos/urls.py and grafts its patterns here.
    # Effectively, every pattern in finos/urls.py becomes a top-level URL.
    #
    # Alternative: path('app/', include('finos.urls')) would put all
    # FIN-OS pages under /app/ — e.g., /app/investor/. We use '' so pages
    # are at the root: /investor/, /trader/, etc.
    path('', include('finos.urls')),
]
